
# PostgreSQL (Car)
datasource.car.url=jdbc:postgresql://localhost:5432/devdb
datasource.car.driver-class-name=org.postgresql.Driver
datasource.car.username=postgres
datasource.car.password=

# JPA settings for Car (PostgreSQL)
datasource.car.jpa.ddl-auto=update
datasource.car.jpa.dialect=org.hibernate.dialect.PostgreSQLDialect
datasource.car.jpa.show-sql=true
vehicle.car.type=Tesla
vehicle.bike.type=Ducati