# -----------------------------------------------
# LOCAL Profile - Dual Datasource
# Car  → PostgreSQL
# Bike → MySQL
# -----------------------------------------------

# Vehicle bean config
vehicle.car.type=Ford
vehicle.bike.type=Yamaha